// Liste des pays avec leurs indicatifs téléphoniques (sans Israël)
export const countries = [
  { code: '+213', name: 'Algérie', flag: '🇩🇿', nameEn: 'Algeria' },
  { code: '+376', name: 'Andorre', flag: '🇦🇩', nameEn: 'Andorra' },
  { code: '+971', name: 'Émirats arabes unis', flag: '🇦🇪', nameEn: 'UAE' },
  { code: '+93', name: 'Afghanistan', flag: '🇦🇫', nameEn: 'Afghanistan' },
  { code: '+1', name: 'États-Unis / Canada', flag: '🇺🇸', nameEn: 'USA/Canada' },
  { code: '+54', name: 'Argentine', flag: '🇦🇷', nameEn: 'Argentina' },
  { code: '+61', name: 'Australie', flag: '🇦🇺', nameEn: 'Australia' },
  { code: '+43', name: 'Autriche', flag: '🇦🇹', nameEn: 'Austria' },
  { code: '+994', name: 'Azerbaïdjan', flag: '🇦🇿', nameEn: 'Azerbaijan' },
  { code: '+32', name: 'Belgique', flag: '🇧🇪', nameEn: 'Belgium' },
  { code: '+226', name: 'Burkina Faso', flag: '🇧🇫', nameEn: 'Burkina Faso' },
  { code: '+359', name: 'Bulgarie', flag: '🇧🇬', nameEn: 'Bulgaria' },
  { code: '+973', name: 'Bahreïn', flag: '🇧🇭', nameEn: 'Bahrain' },
  { code: '+387', name: 'Bosnie-Herzégovine', flag: '🇧🇦', nameEn: 'Bosnia' },
  { code: '+375', name: 'Biélorussie', flag: '🇧🇾', nameEn: 'Belarus' },
  { code: '+55', name: 'Brésil', flag: '🇧🇷', nameEn: 'Brazil' },
  { code: '+41', name: 'Suisse', flag: '🇨🇭', nameEn: 'Switzerland' },
  { code: '+86', name: 'Chine', flag: '🇨🇳', nameEn: 'China' },
  { code: '+225', name: 'Côte d\'Ivoire', flag: '🇨🇮', nameEn: 'Ivory Coast' },
  { code: '+237', name: 'Cameroun', flag: '🇨🇲', nameEn: 'Cameroon' },
  { code: '+242', name: 'Congo', flag: '🇨🇬', nameEn: 'Congo' },
  { code: '+243', name: 'RD Congo', flag: '🇨🇩', nameEn: 'DR Congo' },
  { code: '+57', name: 'Colombie', flag: '🇨🇴', nameEn: 'Colombia' },
  { code: '+420', name: 'République tchèque', flag: '🇨🇿', nameEn: 'Czech Republic' },
  { code: '+49', name: 'Allemagne', flag: '🇩🇪', nameEn: 'Germany' },
  { code: '+253', name: 'Djibouti', flag: '🇩🇯', nameEn: 'Djibouti' },
  { code: '+45', name: 'Danemark', flag: '🇩🇰', nameEn: 'Denmark' },
  { code: '+20', name: 'Égypte', flag: '🇪🇬', nameEn: 'Egypt' },
  { code: '+34', name: 'Espagne', flag: '🇪🇸', nameEn: 'Spain' },
  { code: '+372', name: 'Estonie', flag: '🇪🇪', nameEn: 'Estonia' },
  { code: '+251', name: 'Éthiopie', flag: '🇪🇹', nameEn: 'Ethiopia' },
  { code: '+358', name: 'Finlande', flag: '🇫🇮', nameEn: 'Finland' },
  { code: '+33', name: 'France', flag: '🇫🇷', nameEn: 'France' },
  { code: '+241', name: 'Gabon', flag: '🇬🇦', nameEn: 'Gabon' },
  { code: '+44', name: 'Royaume-Uni', flag: '🇬🇧', nameEn: 'UK' },
  { code: '+995', name: 'Géorgie', flag: '🇬🇪', nameEn: 'Georgia' },
  { code: '+233', name: 'Ghana', flag: '🇬🇭', nameEn: 'Ghana' },
  { code: '+224', name: 'Guinée', flag: '🇬🇳', nameEn: 'Guinea' },
  { code: '+30', name: 'Grèce', flag: '🇬🇷', nameEn: 'Greece' },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰', nameEn: 'Hong Kong' },
  { code: '+385', name: 'Croatie', flag: '🇭🇷', nameEn: 'Croatia' },
  { code: '+36', name: 'Hongrie', flag: '🇭🇺', nameEn: 'Hungary' },
  { code: '+62', name: 'Indonésie', flag: '🇮🇩', nameEn: 'Indonesia' },
  { code: '+353', name: 'Irlande', flag: '🇮🇪', nameEn: 'Ireland' },
  { code: '+91', name: 'Inde', flag: '🇮🇳', nameEn: 'India' },
  { code: '+964', name: 'Irak', flag: '🇮🇶', nameEn: 'Iraq' },
  { code: '+98', name: 'Iran', flag: '🇮🇷', nameEn: 'Iran' },
  { code: '+354', name: 'Islande', flag: '🇮🇸', nameEn: 'Iceland' },
  { code: '+39', name: 'Italie', flag: '🇮🇹', nameEn: 'Italy' },
  { code: '+962', name: 'Jordanie', flag: '🇯🇴', nameEn: 'Jordan' },
  { code: '+81', name: 'Japon', flag: '🇯🇵', nameEn: 'Japan' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', nameEn: 'Kenya' },
  { code: '+996', name: 'Kirghizistan', flag: '🇰🇬', nameEn: 'Kyrgyzstan' },
  { code: '+855', name: 'Cambodge', flag: '🇰🇭', nameEn: 'Cambodia' },
  { code: '+82', name: 'Corée du Sud', flag: '🇰🇷', nameEn: 'South Korea' },
  { code: '+965', name: 'Koweït', flag: '🇰🇼', nameEn: 'Kuwait' },
  { code: '+961', name: 'Liban', flag: '🇱🇧', nameEn: 'Lebanon' },
  { code: '+423', name: 'Liechtenstein', flag: '🇱🇮', nameEn: 'Liechtenstein' },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', nameEn: 'Sri Lanka' },
  { code: '+231', name: 'Libéria', flag: '🇱🇷', nameEn: 'Liberia' },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸', nameEn: 'Lesotho' },
  { code: '+370', name: 'Lituanie', flag: '🇱🇹', nameEn: 'Lithuania' },
  { code: '+352', name: 'Luxembourg', flag: '🇱🇺', nameEn: 'Luxembourg' },
  { code: '+371', name: 'Lettonie', flag: '🇱🇻', nameEn: 'Latvia' },
  { code: '+218', name: 'Libye', flag: '🇱🇾', nameEn: 'Libya' },
  { code: '+212', name: 'Maroc', flag: '🇲🇦', nameEn: 'Morocco' },
  { code: '+377', name: 'Monaco', flag: '🇲🇨', nameEn: 'Monaco' },
  { code: '+373', name: 'Moldavie', flag: '🇲🇩', nameEn: 'Moldova' },
  { code: '+261', name: 'Madagascar', flag: '🇲🇬', nameEn: 'Madagascar' },
  { code: '+223', name: 'Mali', flag: '🇲🇱', nameEn: 'Mali' },
  { code: '+95', name: 'Myanmar', flag: '🇲🇲', nameEn: 'Myanmar' },
  { code: '+976', name: 'Mongolie', flag: '🇲🇳', nameEn: 'Mongolia' },
  { code: '+222', name: 'Mauritanie', flag: '🇲🇷', nameEn: 'Mauritania' },
  { code: '+356', name: 'Malte', flag: '🇲🇹', nameEn: 'Malta' },
  { code: '+230', name: 'Maurice', flag: '🇲🇺', nameEn: 'Mauritius' },
  { code: '+960', name: 'Maldives', flag: '🇲🇻', nameEn: 'Maldives' },
  { code: '+52', name: 'Mexique', flag: '🇲🇽', nameEn: 'Mexico' },
  { code: '+60', name: 'Malaisie', flag: '🇲🇾', nameEn: 'Malaysia' },
  { code: '+258', name: 'Mozambique', flag: '🇲🇿', nameEn: 'Mozambique' },
  { code: '+264', name: 'Namibie', flag: '🇳🇦', nameEn: 'Namibia' },
  { code: '+227', name: 'Niger', flag: '🇳🇪', nameEn: 'Niger' },
  { code: '+234', name: 'Nigéria', flag: '🇳🇬', nameEn: 'Nigeria' },
  { code: '+31', name: 'Pays-Bas', flag: '🇳🇱', nameEn: 'Netherlands' },
  { code: '+47', name: 'Norvège', flag: '🇳🇴', nameEn: 'Norway' },
  { code: '+977', name: 'Népal', flag: '🇳🇵', nameEn: 'Nepal' },
  { code: '+64', name: 'Nouvelle-Zélande', flag: '🇳🇿', nameEn: 'New Zealand' },
  { code: '+968', name: 'Oman', flag: '🇴🇲', nameEn: 'Oman' },
  { code: '+507', name: 'Panama', flag: '🇵🇦', nameEn: 'Panama' },
  { code: '+51', name: 'Pérou', flag: '🇵🇪', nameEn: 'Peru' },
  { code: '+63', name: 'Philippines', flag: '🇵🇭', nameEn: 'Philippines' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', nameEn: 'Pakistan' },
  { code: '+48', name: 'Pologne', flag: '🇵🇱', nameEn: 'Poland' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹', nameEn: 'Portugal' },
  { code: '+595', name: 'Paraguay', flag: '🇵🇾', nameEn: 'Paraguay' },
  { code: '+974', name: 'Qatar', flag: '🇶🇦', nameEn: 'Qatar' },
  { code: '+40', name: 'Roumanie', flag: '🇷🇴', nameEn: 'Romania' },
  { code: '+381', name: 'Serbie', flag: '🇷🇸', nameEn: 'Serbia' },
  { code: '+7', name: 'Russie', flag: '🇷🇺', nameEn: 'Russia' },
  { code: '+250', name: 'Rwanda', flag: '🇷🇼', nameEn: 'Rwanda' },
  { code: '+966', name: 'Arabie saoudite', flag: '🇸🇦', nameEn: 'Saudi Arabia' },
  { code: '+249', name: 'Soudan', flag: '🇸🇩', nameEn: 'Sudan' },
  { code: '+46', name: 'Suède', flag: '🇸🇪', nameEn: 'Sweden' },
  { code: '+65', name: 'Singapour', flag: '🇸🇬', nameEn: 'Singapore' },
  { code: '+386', name: 'Slovénie', flag: '🇸🇮', nameEn: 'Slovenia' },
  { code: '+421', name: 'Slovaquie', flag: '🇸🇰', nameEn: 'Slovakia' },
  { code: '+221', name: 'Sénégal', flag: '🇸🇳', nameEn: 'Senegal' },
  { code: '+252', name: 'Somalie', flag: '🇸🇴', nameEn: 'Somalia' },
  { code: '+963', name: 'Syrie', flag: '🇸🇾', nameEn: 'Syria' },
  { code: '+228', name: 'Togo', flag: '🇹🇬', nameEn: 'Togo' },
  { code: '+66', name: 'Thaïlande', flag: '🇹🇭', nameEn: 'Thailand' },
  { code: '+992', name: 'Tadjikistan', flag: '🇹🇯', nameEn: 'Tajikistan' },
  { code: '+993', name: 'Turkménistan', flag: '🇹🇲', nameEn: 'Turkmenistan' },
  { code: '+216', name: 'Tunisie', flag: '🇹🇳', nameEn: 'Tunisia' },
  { code: '+90', name: 'Turquie', flag: '🇹🇷', nameEn: 'Turkey' },
  { code: '+886', name: 'Taïwan', flag: '🇹🇼', nameEn: 'Taiwan' },
  { code: '+255', name: 'Tanzanie', flag: '🇹🇿', nameEn: 'Tanzania' },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦', nameEn: 'Ukraine' },
  { code: '+256', name: 'Ouganda', flag: '🇺🇬', nameEn: 'Uganda' },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', nameEn: 'Uruguay' },
  { code: '+998', name: 'Ouzbékistan', flag: '🇺🇿', nameEn: 'Uzbekistan' },
  { code: '+58', name: 'Venezuela', flag: '🇻🇪', nameEn: 'Venezuela' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', nameEn: 'Vietnam' },
  { code: '+967', name: 'Yémen', flag: '🇾🇪', nameEn: 'Yemen' },
  { code: '+27', name: 'Afrique du Sud', flag: '🇿🇦', nameEn: 'South Africa' },
  { code: '+260', name: 'Zambie', flag: '🇿🇲', nameEn: 'Zambia' },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼', nameEn: 'Zimbabwe' },
].sort((a, b) => a.name.localeCompare(b.name));

// Fonction pour extraire l'indicatif et le numéro d'un numéro complet
export const parsePhoneNumber = (fullNumber) => {
  if (!fullNumber) return { code: '+33', number: '' };
  
  // Trouver le pays correspondant
  const country = countries.find(c => fullNumber.startsWith(c.code));
  
  if (country) {
    return {
      code: country.code,
      number: fullNumber.substring(country.code.length)
    };
  }
  
  // Par défaut, retourner France
  return { code: '+33', number: fullNumber };
};
